name: Generate trophy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Trophy SVG
        # You can add API parameters like &theme=onedark or &no-bg=true to this URL
        run: curl -s "https://github-profile-trophy.vercel.app/?username=Soura1345" -o trophy.svg

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add trophy.svg
          git commit -m "Update trophy" || exit 0
          git push
